---
- name: Find existing Storage Domains in Datacenter
  ovirt_storage_domains_facts:
    auth: "{{ ovirt_auth }}"
    pattern: "datacenter={{ data_center_name }}"

- name: Remove Storage Domains apart from master and hosted_engine storage (if HE is used)
  ovirt_storage_domains:
    state: absent
    id: "{{ ovirt_item.id }}"
    auth: "{{ ovirt_auth }}"
    format: "{{ format_storages }}"
  with_items: "{{ ovirt_storage_domains }}"
  when:
    - not ovirt_item.master
    - not hosted_engine or ovirt_item.id != hosted_engine_sd_id
  loop_control:
    loop_var: ovirt_item

- name: Put in maintainance master Storage Domain
  ovirt_storage_domains:
    state: maintenance
    id: "{{ ovirt_item.id }}"
    data_center: "{{ data_center_name }}"
    auth: "{{ ovirt_auth }}"
  with_items: "{{ ovirt_storage_domains }}"
  when:
    - ovirt_item.master
    - not hosted_engine
  loop_control:
    loop_var: ovirt_item
